"""empty message

Revision ID: ab5d38606780
Revises: 7afab587344d
Create Date: 2020-05-09 19:54:20.449442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5d38606780'
down_revision = '7afab587344d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'done')
    # ### end Alembic commands ###
